# Generated by Django 5.0.6 on 2024-08-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
